// src/App.svelte
<script>
  import Footer from "./lib/Footer.svelte";
  import Navbar from "./lib/Navbar.svelte";
  import Portfolio from "./lib/Portfolio.svelte";
  import Summary from "./lib/Summary.svelte";
  import Timeline from "./lib/Timeline.svelte";
</script>

<main>
  <Navbar />
  <Summary />
  <Portfolio />
  <Timeline />
  <Footer />
</main>

<style>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>

// src/App.jsx
import Contact from "./components/Contact";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Navigation from "./components/Navbar";
import Portfolio from "./components/Portfolio";
import Timeline from "./components/Timeline";

function App() {
  return (
    <>
      <Navigation />
      <div className="px-2 md:px-0">
        <Header />
        <Portfolio />
        <Timeline />
        {/* <Contact /> */}
        {/* <Footer /> */}
      </div>
    </>
  )
}

export default App
